config/routes.rb
Flixter::Application.routes.draw do
  devise_for :users
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  get 'privacy', :to => 'static_pages#privacy'
  get 'about', :to => 'static_pages#about'
  get 'team', :to => 'static_pages#team'
  get 'career', :to => 'static_pages#career'
  resources :user_profiles, :only => [:new, :create, :update]
  resources :courses, :only => [:index, :show] do
    resources :enrollments, :only => :create
  end
  resources :lessons, :only => [:show]
  namespace :instructor do
    resources :lessons, :only => [:update]
    resources :sections, :only => [:update] do
      resources :lessons, :only => [:create]
    end    
    resources :courses, :only => [:new, :create, :show] do
      resources :sections, :only => [:create]
    end
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/course.rb
class Course < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	
	belongs_to :user
	has_many :sections
	has_many :images
	has_many :enrollments

	validates :title, :presence => true
	validates :description, :presence => true
	validates :cost, :presence => true, :numericality => {:greater_than_or_equal_to => 0}

	def free?
		cost.zero?
	end

	def premium?
		! free?
	end
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :course
	belongs_to :user
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	belongs_to :section
	mount_uploader :video, VideoUploader

	include RankedModel
	ranks :row_order, :with_same => :section_id

	def next_lesson
		lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
		if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    
		return lesson
	end

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/section.rb
class Section < ActiveRecord::Base
	belongs_to :course
	has_many :lessons

	include RankedModel
	ranks :row_order, :with_same => :course_id

	def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first

    return section
  end
	
end

app/models/user.rb
class User < ActiveRecord::Base
has_one :user_profile
has_many :courses
has_many :enrollments
has_many :enrolled_courses, :through => :enrollments, :source => :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end



end 

app/models/user_profile.rb
class User_profile < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	before_action :authenticate_user!

	def show
	end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_enrollment_for_current_lesson, :only => [:show]

	def show
	end

	private

	helper_method :current_lesson
	def current_lesson
		@current_lesson ||= Lesson.find(params[:id])
	end

	def require_enrollment_for_current_lesson
    	if current_user.enrolled_in?(current_lesson.section.course) != true
       		redirect_to course_path(current_lesson.section.course), :alert => 'You must enroll in the course to view lesson material!'
     	end
  	end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flixter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="http://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.12/video.js"></script>
    <style>
      .video-js {padding-top: 56.25%}
      .vjs-fullscreen {padding-top: 0px}
    </style>
</head>
<body>

<div id="wrap">
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FLIXTER', root_path, :class => 'navbar-brand'%>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Courses', courses_path%> <span class="sr-only">(current)</span></a></li>
        <li><%= link_to 'About', about_path %></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-list"></span> User Menu</a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? %>
            <li><%= link_to 'My Dashboard', dashboard_path %></li>
            <li><%= link_to 'Teach a Class', new_instructor_course_path %></li>
            <li><%= link_to 'Profile', new_user_profile_path %></li>
                <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                  <li><%=  current_user.email %></li>
            <% else %>
              <li><a data-toggle="modal" href="#signinModal">Sign In</a></li>
              <li><a data-toggle="modal" href="#signupModal">Sign Up</a></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
<p class="alert alert-danger"><%= alert %></p>
<% end %> 

<%= yield %>

</div>

<br class="clr" />
  
<div id="footer">
    <div class="container">
      <div class="col-xs-12 col-sm-3">
        <b>Teachers</b>
        <br />
        <%= link_to 'Teach a Course', new_instructor_course_path %>
        <br />
        <%= link_to 'User Dashboard', dashboard_path %>
      </div>
      <div class="col-xs-12 col-sm-3">
        <b>About</b>
        <br />
        <%= link_to 'Team', team_path %>
        <br />
        <%= link_to 'About', about_path %>
        <br />
        <%= link_to 'Privacy Policy', privacy_path %>
      </div>
      <div class="col-xs-12 col-sm-3">
        <b>Contact</b>
        <br />
        rossrobertmckee@gmail.com
        <br />
        24 Hospital Circle
        <br />
        Danbury, CT 06810
      </div>
      <div class="col-xs-12 col-sm-3 social">
        <b>Social</b>
        <br />
        <%= link_to 'http://github.com/rossrobertmckee' do %>
          <%= image_tag 'github.png', :class => 'social-button' %>
        <% end %>
        <%= image_tag 'facebook.png', :class => 'social-bustton' %>
        <%= image_tag 'twitter.png', :class => 'social-button' %>
      </div>
    </div>
</div>


<!-- Modal -->
<div id="signinModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
         <h4><span class="glyphicon glyphicon-user"></span> Login (Welcome Back!)</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(:user, :url => user_session_path) do |f| %>
          <div class="inputs">
            <%= f.input :email, :required => false, :autofocus => true %>
            <%= f.input :password, :required => false %>
          </div>
      </div>
      <div class="modal-footer">
         <%= f.button :submit, "Sign in", :class => 'btn btn-primary' %>
        <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>


<!-- Modal -->
<div id="signupModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
         <h4><span class="glyphicon glyphicon-edit"></span> Sign up! (A smart idea, btw)</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(:user, :url => user_registration_path) do |f| %>
          <div class="inputs">
            <%= f.input :email, :required => false, :autofocus => true %>
            <%= f.input :user_name, :required => false %>
            <%= f.input :password, :required => false %>
            <%= f.input :password_confirmation %>
          </div>
      </div>
      <div class="modal-footer">
         <%= f.button :submit, "Sign Me Up!", :class => 'btn btn-primary' %>
        <% end %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>



</body>
</html>